#!/bin/bash

cur_time=`date +%F-%H-%M-%S`

tar -cvj \
	~/.mypass.kdb \
	~/.mozilla/firefox \
	~/.thunderbird \
	~/dev/univer \
	~/.gnupg \
	~/virt \
	~/vps \
	~/.i2p \
	~/.xchat2 \
	~/.config/PyBitmessage | \
	gpg -r russianbruteforce@gmail.com -e | \
	gpg -c --cipher-algo CAMELLIA256 - > "$cur_time.backup"
